//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Id { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> Id_of_Student_FK_ { get; set; }
        public Nullable<int> Id_of_Discipline_FK_ { get; set; }
    }
}
