//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Students2Entities : DbContext
    {
        public Students2Entities()
            : base("name=Students2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Scholarship> Scholarship { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Types_of_scholarships> Types_of_scholarships { get; set; }
    
        public virtual ObjectResult<sp_scholars_Result> sp_scholars(Nullable<int> id_type_of_scholarship)
        {
            var id_type_of_scholarshipParameter = id_type_of_scholarship.HasValue ?
                new ObjectParameter("Id_type_of_scholarship", id_type_of_scholarship) :
                new ObjectParameter("Id_type_of_scholarship", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_scholars_Result>("sp_scholars", id_type_of_scholarshipParameter);
        }
    }
}
