//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string full_name { get; set; }
        public Nullable<int> num_of_grade_book { get; set; }
        public string foundation_of_study { get; set; }
        public Nullable<int> course { get; set; }
        public string scholarship { get; set; }
    }
}
